image: golang:latest

stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - apt update -y && apt install gcc xorg-dev libgl1-mesa-dev -y
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - mkdir -p mybinaries
    - go build -o mybinaries ./...
  # artifacts:
  #   paths:
  #     - mybinaries

pages:
  stage: deploy
  script:
    - go install golang.org/x/tools/cmd/godoc@latest     
    - mkdir public
    - GO_MODULE=jschan GO_DOC_HTML_OUTPUT=public ./godoc_static.sh
  artifacts:
    paths:
      - public
